// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJPcqowvmhshHBIWAYXC-ObmP2pqpTJM',
    appId: '1:34173947519:web:293da2af099ee5293cb94a',
    messagingSenderId: '34173947519',
    projectId: 'userselectionapp',
    authDomain: 'userselectionapp.firebaseapp.com',
    databaseURL: 'https://userselectionapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'userselectionapp.firebasestorage.app',
    measurementId: 'G-9HDEYNWCM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBkA688rCv5v2He0hpdPAB1tymsSuI4Mw',
    appId: '1:34173947519:android:3a5c92c3fd9355333cb94a',
    messagingSenderId: '34173947519',
    projectId: 'userselectionapp',
    databaseURL: 'https://userselectionapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'userselectionapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dFrIAU78PDU3mL1bhLpzRjhMydBFH7k',
    appId: '1:34173947519:ios:9d3082dc12e0105a3cb94a',
    messagingSenderId: '34173947519',
    projectId: 'userselectionapp',
    databaseURL: 'https://userselectionapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'userselectionapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterBarcodeReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dFrIAU78PDU3mL1bhLpzRjhMydBFH7k',
    appId: '1:34173947519:ios:92421555dcf7d7103cb94a',
    messagingSenderId: '34173947519',
    projectId: 'userselectionapp',
    databaseURL: 'https://userselectionapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'userselectionapp.firebasestorage.app',
    iosBundleId: 'com.dynamsoft.flutterBarcodeSdkExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaJPcqowvmhshHBIWAYXC-ObmP2pqpTJM',
    appId: '1:34173947519:web:374d84afa86bdfaa3cb94a',
    messagingSenderId: '34173947519',
    projectId: 'userselectionapp',
    authDomain: 'userselectionapp.firebaseapp.com',
    databaseURL: 'https://userselectionapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'userselectionapp.firebasestorage.app',
    measurementId: 'G-3FQRCFCEQN',
  );
}
